spring:
  application:
    name: graphql-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/test?autoReconnect=true&useSSL=false
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
